### ISSUE TITLE
Crash in MR.Gestures.AbsoluteLayout.get_TappedCommandParameter()

### ISSUE THREAD

**Issue by patook** [MichaelRumpler/GestureSample#1]
Hi -

Here is the crash stack. The error might be due to an XF bug but maybe you can check for null or wrap this around try/catch.

We've had 33 crashes already and can't try/catch them ourselves.
**Crash Log**:
System.NullReferenceExceptionObject reference not set to an instance of an object

Xamarin.Forms.BindableObject.GetValue(BindableProperty property)
MR.Gestures.AbsoluteLayout.get_TappedCommandParameter()
MR.Gestures.GestureHandler.OnTapped(TapEventArgs args)
MR.Gestures.GestureThrottler.OnTapped(TapEventArgs args)
at MR.Gestures.iOS.iOSGestureHandler+<>c__DisplayClass24_0+<b__0>d.MoveNext () <0x1011a754c + 0x001c3> in :0

**Sample Code:**
viewLayout.Tapped += (object sender, MR.Gestures.TapEventArgs e) => {
                    try {
                        if (OnClickProfile != null) {
                            OnClickProfile.Execute (m.UserName);
                        }
                    } catch (Exception ex) {
                        App.Report (ex);
                    }
                };

**Comment by MichaelRumpler** [comment]
Added a workaround in version 1.3.3.
