### ISSUE TITLE
MR.Gestures ScrollView nullreference exception

### ISSUE THREAD

**Issue by japero** [MichaelRumpler/GestureSample#10]
When using latest 2.1.0 version I get this error when using swipe in scrollview.
I reverted to 2.0.0 version and error disappears. 
I saw similar error on earlier versions and commented over there also.

**Comment by MichaelRumpler** [comment]
A little more information would be helpful.

When do you get the NRE? Do you have a stack trace? Can you send me a repro project?

**Comment by japero** [comment]
I can try to make simple demo app and see does it happen there also. But this appears in quite complex view taht has multiple grids and labels in use. I have this MR.Gestures.ScrollView that holds grid inside with label etc. I have Swiped event registered in xaml.
I cannot get stack trace because error happens inside your component? Vs2017 shows only this NullReference exception and app crashes. I have break point in event handler but that is never reach.

**Comment by MichaelRumpler** [comment]
Even if it happens within MR.Gestures you should still get a StackTrace, just without line numbers. It should be written to the output window.

With what you provided I don't even know where to start. So please send me a repro project so that I can debug it.

The platform would help too.

**Comment by japero** [comment]
Ok I will make one and platform is Android with xamarin.forms

Hanki Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by japero** [comment]
Hi, 
I tested this with blank project and error didi not happen there. I will close this issue even though in our compnay project this NullReference exception occures after swipe effect. Must be some other component causing error. Below is all I can get from this error when it is happening.

02-08 09:24:53.265 D/ViewRootImpl@b6164bf[MainActivity](27937): ViewPostImeInputStage processPointer 0
02-08 09:24:53.272 D/Mono    (27937): DllImport searching in: '__Internal' ('(null)').
02-08 09:24:53.272 D/Mono    (27937): Searching for 'java_interop_jnienv_call_nonvirtual_long_method_a'.
02-08 09:24:53.272 D/Mono    (27937): Probing 'java_interop_jnienv_call_nonvirtual_long_method_a'.
02-08 09:24:53.272 D/Mono    (27937): Found as 'java_interop_jnienv_call_nonvirtual_long_method_a'.
Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object.

I reverted to 2.0.0 version because for some reason that I do not know error does not happen.
Sorry that I could not provide reason for this.

Thread finished: <Thread Pool> #21

**Comment by MichaelRumpler** [comment]
These messages are not related to MR.Gestures at all. That's nothing which helps to locate the error.
You might be able to find more info in the device log.

**Comment by japero** [comment]
I thought so too. Very odd this error but I will try to locate reason for this. Thanks for fast responses!

**Comment by kiwicodemonkey** [comment]
Am experiencing the same crash with Xamarin 3.6/Android 9.0/MR.Gestures 2.1.0. iOS works fine.
ContentPage contains MR.ScrollView which contains Vertical stacklayout.
Swiping outside scrollview works, but inside scrollview gives the following stack:

System.NullReferenceException
Object reference is not set to an instance of an object
  at MR.Gestures.Android.EventArgs.AndroidEventArgsHelper.GetTouches (Android.Views.MotionEvent current) [0x00006] in <c63931d951104a8ba883711522cfb229>:0 
  at MR.Gestures.Android.EventArgs.AndroidPanEventArgs..ctor (Android.Views.MotionEvent previous, Android.Views.MotionEvent current, MR.Gestures.PanEventArgs prevArgs, Android.Views.View view) [0x0003a] in <c63931d951104a8ba883711522cfb229>:0 
  at MR.Gestures.Android.SimpleGestureListener.OnScroll (Android.Views.MotionEvent down, Android.Views.MotionEvent move, System.Single distanceX, System.Single distanceY) [0x00025] in <c63931d951104a8ba883711522cfb229>:0 
  at Android.Views.GestureDetector+SimpleOnGestureListener.n_OnScroll_Landroid_view_MotionEvent_Landroid_view_MotionEvent_FF (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e1, System.IntPtr native_e2, System.Single distanceX, System.Single distanceY) [0x00019] in <266395aeef1642bab2007ca31686faf9>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.93(intptr,intptr,intptr,intptr,single,single)

**Comment by PaulVrugt** [comment]
@MichaelRumpler  please reopen this. We experience the exact same issue as @kiwicodemonkey

**Comment by MichaelRumpler** [comment]
I cannot reproduce it. Send me a repro project and I will have a look at it.

**Comment by PaulVrugt** [comment]
I cannot reproduce it either in a test case, but we have tens of crashes from customers in our app in production. We tried on several devices and are unable to reproduce it. Isn't the stacktrace enough info to deduce what's going wrong?

**Comment by MichaelRumpler** [comment]
The stack trace tells me, that the current MotionEvent is null, but I don't know why. For the past five years it was not null. I need to debug that, so I need to reproduce it.

**Comment by PaulVrugt** [comment]
@MichaelRumpler 
I am now able to reproduce it in our application reliably by swiping around for a while in a mr scrollview below the contents in the scrollview. Please let me know if you can reproduce it like this. If not, i'll try to create a repro app

**Comment by PaulVrugt** [comment]
@MichaelRumpler 
I've created a repro project. The repro was very easy. Just run the android project, wait for it to load and swipe a bit below the blue bar

Don't be confused by the project name, it was originally a test project for something else ;)

[CollectionViewSpacing.zip](https://github.com/MichaelRumpler/GestureSample/files/3818553/CollectionViewSpacing.zip)

**Comment by PaulVrugt** [comment]
@MichaelRumpler any updates? Were you able to reproduce it with my repro project?

**Comment by MichaelRumpler** [comment]
Yes, I could reproduce it and am looking into it now. Thanks for that repro project!

**Comment by MichaelRumpler** [comment]
Version 2.1.1 is now available on NuGet.

**Comment by PaulVrugt** [comment]
Thanks, we'll try it out!
