### ISSUE TITLE
"Up" Event blocks underlying UI elements on iOS (Xamrin.Forms)

### ISSUE THREAD

**Issue by Glomby** [MichaelRumpler/GestureSample#13]
I'm using an "Up" Event as part of a ContentView which works perfectly fine. However within the ContentView is a Slider. On iOS only, after the Event fires the slider doesn't respond anymore (it as long as I don't lift my finger I can keep using the slider), the event however keeps working as expected.

I basically need the Up Event for the slider but sliders aren't supported by Mr.Gesture on iOS. This was supposed to be a workaround but when it behaves like that it won't work either. Is there a better way to get an Up event for a slider control working without freezing the slider?

Here is the basic structure of the setup right now. Basically If I could raise the Up event directly from the slider I wouldn't use the contenview container:

`<mr:ContentView Up="SaveP1">
     <Slider  Value="{Binding ****}"/>
 </mr:ContentView>`

**Comment by MichaelRumpler** [comment]
This is the reason why the Slider is red in the [Compatibility list](https://www.mrgestures.com/#Compatibility).

If I add my own `DownUpGestureRecoginzer`, then this breaks some native elements. The `UISlider`, `UIStepper` and `UIButton` are especially sensitive in this regard. I played with this quite a while, but didn't find a workaround.

I return true from `ShouldRecognizeSimultaneously` and set `CancelsTouchesInView` to false. I don't know what else I could do, but if somebody has an idea, I'd be happy to try it.

This actually used to work in some old iOS version, but at some point in time Apple changed something and now I have these problems. I even remember seeing a WWDC session where they mentioned those three elements I listed above, but there was no workaround provided. Unfortunately I can't remember which session that was.

**Comment by Glomby** [comment]
Thanks for the reply. I saw the red mark on the list and was kinda expecting that this workaround might be to easy to fix such an issue.
However, while searching for an alternative solution I discovered that Xamarin actually has a DragCompleted Event for sliders now. I needed to update Xamarin.Forms to version 3.6 (newest release). So at least there is a working alternative now.

**Comment by MichaelRumpler** [comment]
Good to know.
I'll look at their code. Maybe I can get something out.
