### ISSUE TITLE
In iOS, TouchUp method does not invoked for child elements

### ISSUE THREAD

**Issue by Lakshminatarajan** [MichaelRumpler/GestureSample#14]
I have custom grid renderer in Mr.Gesture content page. In iOS, GridExtRenderer has the following override methods.

  ```
  public class GridExtRenderer : VisualElementRenderer<GridExt>
    {
        public GridExtRenderer()  
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<GridExt> e)
        {
            base.OnElementChanged(e);
        }

        public override void TouchesBegan(NSSet touches, UIEvent evt)
        {
            base.TouchesBegan(touches, evt);
        }

        public override void TouchesMoved(NSSet touches, UIEvent evt)
        {
            base.TouchesMoved(touches, evt);
        }

        public override void TouchesEnded(NSSet touches, UIEvent evt)
        {
            base.TouchesEnded(touches, evt);
        }

        public override void TouchesCancelled(NSSet touches, UIEvent evt)
        {
            base.TouchesCancelled(touches, evt);
        }
    }
```

While doing simple drag using touch, TouchesBegan and TouchesMoved method is called. But TouchesEnded method did not gets invoked. After ToucesMoved  gets called, the touch is passed to TouchUp event handler of Mr.Gestures only and not the child event. Repeat the process for second time, now it will not invoke any of the touch events again whereas TouchesEnded doesn’t invoke one time also which is needed for our implementation.

The issue reporting sample in the attachment.
[Sample.zip](https://github.com/MichaelRumpler/GestureSample/files/3202473/Sample.zip)

**Comment by GnanaPriyaNamasivayam** [comment]
@MichaelRumpler , Any update on this..

**Comment by MichaelRumpler** [comment]
I could reproduce the problem, but don't know why your handlers are not called. I don't use those methods in my renderers at all. I add `UIGestureRecognizer`s and use the TouchesBegan/-Ended/-Cancelled methods there. Maybe you can try that. Or you don't use those methods, but use the MR.Gestures events instead.

**Comment by Lakshminatarajan** [comment]
@MichaelRumpler ,

Sorry for late respond from us. 

We have custom control(SfListView) with own events like Tapping, DoubleTapping,ItemHolding,Swiping,Dragging,Selection..etc,. When our customer trying to use Mr.Gesture along with SfListView in ContentPage, Swiping event in ListView  does not fire because of the touch handled in Mr.Gesture’s Down event. When Down event is hooked, ListView didn’t receive any swipe notification. Can you please look further into the reported issue and provide possible work around. We have attached the model sample with SfListview for your reference, please refer the sample from below.

Sample Link : [ListViewSample with MR.Gesture](https://www.syncfusion.com/downloads/support/directtrac/general/ze/Listview1273493662)
