### ISSUE TITLE
ios contentpage swipe event not triggering

### ISSUE THREAD

**Issue by pts1989** [MichaelRumpler/GestureSample#15]
I have a master detail page. The detail page is of the type contentpage. When i try to swipe in iOS, the swipe event is not triggerd. Any way to make sure it will trigger?
`<mr:ContentPage  xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:sys="clr-namespace:System;assembly=mscorlib"
              xmlns:mr="clr-namespace:MR.Gestures;assembly=MR.Gestures"
                 Swiped="ContentPage_Swiped"`

Or is this not possible on iOS?

**Comment by MichaelRumpler** [comment]
The `UISplitViewController` (the native iOS element which is used to render a `MasterDetailPage`) consumes the swipe gestures to handle opening the master page. The information never reaches my gesture handlers.
Unfortunately I don't know a workaround for this.
