### ISSUE TITLE
Listview longPressed item position 

### ISSUE THREAD

**Issue by sateeshtec** [MichaelRumpler/GestureSample#2]
Hi ,
 I am not getting long pressed item position in listview, Can you please suggest me to how to get long pressed item position in Mr listview.

Thanks&Regards,
sateesh

**Comment by MichaelRumpler** [comment]
Hi,

see http://www.mrgestures.com/#EmptyEventArgs

Regards,

Michael

**Comment by keytronic** [comment]
I don't understand how to get item position after long pressing .. Can you give me more informations ?

Thanks
