### ISSUE TITLE
In iOS, TouchUp method does not invoked for child elements (ListView)

### ISSUE THREAD

**Issue by Lakshminatarajan** [MichaelRumpler/GestureSample#20]
Sorry for late respond. We have opened this issue for following up the closed issue further (https://github.com/MichaelRumpler/GestureSample/issues/14) since we expect some additional guidance or solution for this.

Please find the pending clarification/solution needed from you.

We have custom control(SfListView) with own events like Tapping, DoubleTapping,ItemHolding,Swiping,Dragging,Selection..etc,. When our customer trying to use Mr.Gesture along with SfListView in ContentPage, Swiping event in ListView does not fire because of the touch handled in Mr.Gesture’s Down event. When Down event is hooked, ListView didn’t receive any swipe notification. Can you please look further into the reported issue and provide possible work around. We have attached the model sample with SfListview for your reference, please refer the sample from below.

**Sample Link** : [ListViewSample with MR.Gesture](https://www.syncfusion.com/downloads/support/directtrac/general/ze/Listview1273493662)

**Comment by mageshyadavm** [comment]
Any reply/update on this ?

**Comment by MichaelRumpler** [comment]
Sorry, I didn't have time to look at your sample project before my vacation. I'll debug it when I come back next week.

**Comment by MichaelRumpler** [comment]
This sample doesn't help because I don't know what you do in your `SfListView`.

However, I looked at the sample from #14 again and there you override the `Touches*` methods. This is not recommended. You should use a `UIGestureRecognizer` instead. See [this forum thread](https://forums.xamarin.com/discussion/58269/touchesended-is-not-called-in-customrenderer-ios).

This works in your first sample:

	public class GridExtRenderer : VisualElementRenderer<GridExt>
	{
		UILongPressGestureRecognizer longPressGr;

		protected override void OnElementChanged(ElementChangedEventArgs<GridExt> e)
		{
			if (longPressGr != null && NativeView != null)
			{
				NativeView.RemoveGestureRecognizer(longPressGr);
				longPressGr = null;
			}

			base.OnElementChanged(e);

			if (e.NewElement != null && this.NativeView != null)
			{
				longPressGr = new UILongPressGestureRecognizer(OnPressed) { MinimumPressDuration = 0 };
				NativeView.AddGestureRecognizer(longPressGr);
			}
		}

		private void OnPressed(UILongPressGestureRecognizer gr)
		{
			Debug.WriteLine($"GridExtRenderer.OnLongPressed: State={gr.State}");
		}
	}

The `State` tells you if the gesture began, ended, was moved (Changed) or cancelled.
