### ISSUE TITLE
tapped in a binded imaged

### ISSUE THREAD

**Issue by rickerk6gdo** [MichaelRumpler/GestureSample#21]
The tappped event doesn fire in the following code

<mr:Image  x:Name="SnapImage"  Source="{Binding SnapImage}"   Margin="20,10,20,10"  HorizontalOptions="End" VerticalOptions = "End" IsVisible="True"
				Tapped="ImageTapped">

				</mr:Image>

if I put a static name to source (i..e somthing.png) it doesn...

thoughts?

**Comment by MichaelRumpler** [comment]
This is basic functionality which works for everybody. Please have a look at the GestureSample how it is done there. If it still doesn't work for you, then add a repro project.

**Comment by rickerk6gdo** [comment]
I noticed the problem is when extra <Grid> tags are around it.  works under 12.4.0.64 but not under 13.x

reporting to microsoft also.

adding repo code
[GestureSample.zip](https://github.com/MichaelRumpler/GestureSample/files/3975665/GestureSample.zip)
