### ISSUE TITLE
App is crashing on TapGestureRecognizer 

### ISSUE THREAD

**Issue by nitud** [MichaelRumpler/GestureSample#22]
I am using MR.Gesture Nuget Package of version 1.4.2.2 in my old project for TApGestureRecognizer to trigger click event.Initially this was working well now my app is crashing and getting below exception 
Attempting to JIT compile method 'DLToolkit.Forms.Controls.FlowListViewInternalCell:AddTapGestureToView (Xamarin.Forms.View)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information
Can anyone help me to fix this issue

**Comment by MichaelRumpler** [comment]
The error message points to https://github.com/daniel-luberda/DLToolkit.Forms.Controls. You should file an issue there.
