### ISSUE TITLE
Pinching/Pinched Gesture not firing

### ISSUE THREAD

**Issue by kcrandall** [MichaelRumpler/GestureSample#23]
I am currently trying to get pinching to work on a BoxView over a cameraview to act as a zoom control. The double tapped and tapped gesture commands are firing properly but my prints aren't getting executed in the pinch commands. 

Xamarin.Forms: 4.2.0.709249
Mr.Gestures: 2.1.0
iOS

**Comment by MichaelRumpler** [comment]
Maybe the camera swallows the events. Can you send me a repro project?

**Comment by kcrandall** [comment]
I don't think that is the problem because the cameras view also has a pinch gesture and if it was capturing them it would zoom as well. The box view completely covers it based on the layout design so the boxview should intercept everything. When I double tap anywhere on the boxview I switch the camera from from to back/front meaning Mr.Gestures is intercepting those touches.

Here is a simple project I just made with it. The boxview is in red. If its run on device it'll take up the entire screen. If on simulator (without camera rendering properly) it'll be smaller.
https://1drv.ms/u/s!AjziusY3OZKThNteS38l4uBUudiOCg?e=BzHuhM

Thanks!

**Comment by MichaelRumpler** [comment]
I tried it on my iPad and the commands are called. Pinching only on the small red BoxView has to be accurate, but it works. I'd recommand making the BoxView higher or moving the Commands to the Grid.

> 2019-11-18 15:07:41.385 PinchTest.iOS[18487:1280346] INFO | 2019-11-18T14:07:41.384079 | CameraPinching command started... | File: D:\Temp\PinchTest\PinchTest\CameraViewModel.cs | Line: 184
> 2019-11-18 15:07:41.387 PinchTest.iOS[18487:1280346] INFO | 2019-11-18T14:07:41.385597 | CameraPinching Old Zoom: 0 | File: D:\Temp\PinchTest\PinchTest\CameraViewModel.cs | Line: 185
> 2019-11-18 15:07:41.389 PinchTest.iOS[18487:1280346] INFO | 2019-11-18T14:07:41.387984 | CameraPinching DeltaScale: 0.987168604555119 | File: D:\Temp\PinchTest\PinchTest\CameraViewModel.cs | Line: 186
> 2019-11-18 15:07:41.390 PinchTest.iOS[18487:1280346] INFO | 2019-11-18T14:07:41.389353 | CameraPinching New Zoom: 0 | File: D:\Temp\PinchTest\PinchTest\CameraViewModel.cs | Line: 188
> 2019-11-18 15:07:41.558 PinchTest.iOS[18487:1280346] INFO | 2019-11-18T14:07:41.557701 | CameraPinched command started... | File: D:\Temp\PinchTest\PinchTest\CameraViewModel.cs | Line: 198
>
