### ISSUE TITLE
Same license key works on IOS but not UWP.

### ISSUE THREAD

**Issue by dbagno** [MichaelRumpler/GestureSample#24]
Followed all documentation to the letter but am getting license not valid on UWP?

**Comment by MichaelRumpler** [comment]
What exactly does the exception say (without the license key)?
Open your Package.appxmanifest in a text editor and set the DisplayName to the app name (twice).

**Comment by dbagno** [comment]
Thanks so much for replying.  I am really counting on this working….

With the license number I get the below error  Without the license number I also get the same error

"The LicenseKey '626T-A8NA-3KL4-7EZF-J5ZH-VHS3-M2ZU-RDJE-VMCG-NLAW-7KFG-XS2B-3GEB' is not for the app 'TEE.EdgeOnSite.UWP'."



"The LicenseKey '626T-A8NA-3KL4-7EZF-J5ZH-VHS3-M2ZU-RDJE-VMCG-NLAW-7KFG-XS2B-3GEB' is not for the app 'TEE.EdgeOnSite.UWP'.”}

<?xml version="1.0" encoding="utf-8"?>

<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  IgnorableNamespaces="uap mp">

  <Identity
    Name="ae595798-f2da-48fe-b707-b4408e748060"
    Publisher="CN=fcd39cbf-50ef-4963-b7f7-c8745db5eaf7"
    Version="1.0.0.0" />

  <mp:PhoneIdentity PhoneProductId="ec0cc741-fd3e-485c-81be-68815c480690" PhonePublisherId="00000000-0000-0000-0000-000000000000"/>

  <Properties>
    <DisplayName>TEE.EdgeOnSite.UWP</DisplayName>
    <PublisherDisplayName>fcd39cbf-50ef-4963-b7f7-c8745db5eaf7</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
  </Properties>

  <Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.0.0" MaxVersionTested="10.0.0.0" />
  </Dependencies>

  <Resources>
    <Resource Language="x-generate"/>
  </Resources>

  <Applications>
    <Application Id="App"
      Executable="$targetnametoken$.exe"
      EntryPoint="TEE.EdgeOnSite.UWP.App">
      <uap:VisualElements
        DisplayName="TEE.EdgeOnSite.UWP"
        Square150x150Logo="Assets\Square150x150Logo.png"
        Square44x44Logo="Assets\Square44x44Logo.png"
        Description="TEE.EdgeOnSite.UWP"
        BackgroundColor="transparent">
        <uap:DefaultTile Wide310x150Logo="Assets\Wide310x150Logo.png" Square310x310Logo="Assets\LargeTile.png" Square71x71Logo="Assets\SmallTile.png">
          <uap:ShowNameOnTiles>
            <uap:ShowOn Tile="square150x150Logo" />
            <uap:ShowOn Tile="wide310x150Logo" />
            <uap:ShowOn Tile="square310x310Logo" />
          </uap:ShowNameOnTiles>
        </uap:DefaultTile>
        <uap:SplashScreen Image="Assets\SplashScreen.png" />
      </uap:VisualElements>
    </Application>
  </Applications>

  <Capabilities>
    <Capability Name="internetClient" />
    <uap:Capability Name="picturesLibrary"/>
  </Capabilities>
</Package>

**Comment by MichaelRumpler** [comment]
You bought a license for TEE.EdgeOnSite and not TEE.EdgeOnSite.UWP.
As I said above search for DisplayName in the .appxmanifest file and remove the ".UWP".

**Comment by dbagno** [comment]
I did as you say and removed UWP and so it will let me register the key without any error.  However when I go to execute the gestures nothing happens.  Keep in mind it works 100 percent ok on IOS
Sorry for bothering you so much

**Comment by MichaelRumpler** [comment]
Then the license key is ok now and I will close this issue.
Please open a new one with the code which does not work for you on UWP.
Did you also check https://www.mrgestures.com/#Compatibility for any controls which are known to not work?

**Comment by dbagno** [comment]
Thanks for your help,  It took a long time to resolve this license issue.  I did not see any mention of changing the app manifest on your website for UWP.  It would be helpful if this information was there.  Do you intend to maintain this plugin.  I work for a leading Edge Construction Software company that needs this cross platform behavior that your plugin provides

https://www.estimatingedge.com <https://www.estimatingedge.com/>

Thanks
Dave

**Comment by MichaelRumpler** [comment]
It took 22 hours to resolve this license issue.
It is in my FAQ on https://www.mrgestures.com/#HowToConfigureAppName. You said you followed it so I told you a different way to change the same settings in the same file.

**Comment by dbagno** [comment]
I reached out to you on this issue a month on Jan 4th.  This is the first time I have heard back from you.  I am glad you responded.  
thanks

**Comment by MichaelRumpler** [comment]
I checked my mailbox and found an email from you from January 7th, 15:07. - I replied 12 minutes later.

**Comment by dbagno** [comment]
Well I apologize, I never got it. Do you plan on maintaining this software package it is very important for the company I work for.  I see a lot of Xamarin plugins get outdated and fade away.
thanks

**Comment by MichaelRumpler** [comment]
Should I ever stop maintaining it, then I'll make it open source.

**Comment by dbagno** [comment]
Thanks I hope you keep up with it,  It is the only gig in town:-)
I have been using Xamarin since it first came out.

**Comment by dbagno** [comment]
Mike
It seems like MRGestures is not working with the latest version of Xcode 11.4.
Thanks
dave
