### ISSUE TITLE
Swipe works inconstantly after update xamarin forms on Android

### ISSUE THREAD

**Issue by IlyaSemenchenko** [MichaelRumpler/GestureSample#25]
After xamarin forms update to one of the latest versions 4.4 or 4.5, we got inconstant behavior when swipe works like 4 of 10 times in stacklayout on Android.
I attached updated GestureSample project where you can reproduce this behaviour on Layout>StackLayout page.
Thanks.
[GestureSample-master.zip](https://github.com/MichaelRumpler/GestureSample/files/4376642/GestureSample-master.zip)

**Comment by MichaelRumpler** [comment]
Thanks for your repro project. Unfortunately I still cannot reproduce it. I tried your project and the GestureSample with XF 4.5.0.495 but both work on my Sony Xperia Z5 Compact and Samsung Galaxy Tab S3.
What device are you using?
Does the Panning event work for you?
You could try tweaking `MR.Gestures.Android.Settings.SwipeVelocityThreshold`.

> The velocity of a lifted finger relative to the ScaledMaximumFlingVelocity must be at least this value to count as Swipe.
> The default value is 0.1. Set it to a higher value if you want the user to move faster.
> The value must be between 0.0 and 1.0.</remarks>
