### ISSUE TITLE
OnPanned stops working on iOS, works fine on Android

### ISSUE THREAD

**Issue by grimmdp** [MichaelRumpler/GestureSample#27]
Hello,
I'm having issues with the OnPanned gesture on iOS. I have a view that I'm sliding up/down using the TranslationY property, which works perfectly on Android, and works for the first drag session on iOS. After that first drag, I stop receiving OnPanned events. Any input greatly appreciated. 
Thanks

 ```    
<RelativeLayout>
         <mr:RelativeLayout Padding="0"                   
                        x:Name="outerFrame"
                        PanningCommand="{Binding PanningCommand}"
                        PannedCommand="{Binding PannedCommand}"
                        RelativeLayout.XConstraint="{ConstraintExpression Type=Constant,Constant=0}"
                        RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToView, ElementName='imgFrame', Property=Y, Factor=1}"
                        RelativeLayout.WidthConstraint="{ConstraintExpression Type=Constant,Constant=114}" 
                        RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToView, ElementName='imgFrame',Property=Height, Factor=1}" 
                        >
                <Image x:Name="ruler"
                        RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToParent, Property=X, Factor=0}"
                        RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent, Property=Y, Factor=0}"
                        RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1}"
                        RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1}"
                        IsVisible="{Binding AllowPartialInput, Mode=OneWay}"
                        Source="{Binding rulerImage}"
                    />
                <mr:Image x:Name="slide"
                        RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToParent, Property=X, Factor=0}"
                        RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent, Property=Y, Factor=0}"
                        RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1}"
                        RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1}"
                        IsVisible="{Binding AllowPartialInput, Mode=OneWay}"
                        Source="{Binding slideImage}"
	                TranslationY="{Binding TranslationY}"
			AnchorY="{Binding AnchorY}"
                    />
            </mr:RelativeLayout>
</RelativeLayout>
```

**Comment by MichaelRumpler** [comment]
What you describe should work and I don’t see any obvious bug in your code.
(Although you have two RelativeLayouts and the slide Image doesn't need to be an mr:Image)

Can you send me a repro project?

**Comment by grimmdp** [comment]
Hi Michael,Sorry it took so long, but I was having problems replicating the issue in a sample project. I was finally able to get it to fail, and the process has illuminated a few things:

    On Friday, May 8, 2020, 10:14:03 AM MDT, Michael Rumpler <notifications@github.com> wrote:  
 
 


What you describe should work and I don’t see any obvious bug in your code.
(Although you have two RelativeLayouts and the slide Image doesn't need to be an mr:Image)

Can you send me a repro project?

**Comment by MichaelRumpler** [comment]
And your findings?

**Comment by MichaelRumpler** [comment]
I got your repro project via email. I don't see any problems with Panning. That works reliably on my iPad.
I do see however that the Buttons don't always raise the TappedCommand.
It seems like the Button swallows some events on iOS. If I change the Buttons to Labels and keep the TappedCommands on them, then it works reliably.

But keep in mind, that I also don’t raise the Tapped event at once. I have to wait 250ms to see if it may be a DoubleTapped event instead. To get the events immediately use TappingCommand.
