### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by ThumbGen** [MichaelRumpler/GestureSample#29]
Hi

I am successfully using your awesome lib for some years now.
Trying to 'migrate' to **AndroidX**, I get one error message:

**Can not resolve reference: `Xamarin.Android.Support.Design`, referenced by `MR.Gestures`. Please add a NuGet package or assembly reference for `Xamarin.Android.Support.Design`, or remove the reference to `MR.Gestures`.**

Any chance to keep both AndroidX support and MR.Gestures in my app?

Thanks a lot!

**Comment by MichaelRumpler** [comment]
I tested that a while ago and it worked out of the box. But I did not update the GestureSample. I did that now. It still uses MR.Gestures 2.1.2.

I actually never used the Android.Support libs myself. I only inherited from Xamarins renderers and some of those used it. But this should resolve itself automatically when you update Xamarin.Forms.

Try deleting all bin and obj folders and compile again. Maybe there's an old XF dll left somewhere. This happens a lot when updating XF.

**Comment by ThumbGen** [comment]
I fetched the GestureSample and switched to targeting Android 10.0 (Q). Then the error happens in the sample too :(  It was the only difference compared to my app.

**Comment by ThumbGen** [comment]
I know it is impolite to 'bump', but I am really in the middle of a big refactoring story and would like to know if I can get "the best of all worlds": MR.Gestures, AndroidX and Android 10.0 target (which is required by other packages)...

**Comment by MichaelRumpler** [comment]
I didn't get an email from your last reply. No time today, so I'll look at it tomorrow.

**Comment by MichaelRumpler** [comment]
I just released version 2.1.3 which includes two different dlls for MonoAndroid90 with the old Android.Support libs and MonoAndroid10.0 with AndroidX. Please give it a try.

**Comment by ThumbGen** [comment]
Thanks a lot! Works perfectly!
