### ISSUE TITLE
Issue with button text color on iOS

### ISSUE THREAD

**Issue by abdelkader27** [MichaelRumpler/GestureSample#3]
Hi,
We are using Mr.Gestures library and we found an issue with the button text color when down/up on iOS.
You can see the behavior on the attached images.
I'm using the button3 in the sample downloaded from github.

![screenshot_1](https://cloud.githubusercontent.com/assets/3541734/15496950/0576bb02-2190-11e6-8a25-ec94af3fae15.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3541734/15496954/0bc7fcc8-2190-11e6-8330-948dc3c5be59.png)

**Comment by MichaelRumpler** [comment]
When you open the Button sample page and you tap the last Button immediately after the page opens, then the text color of the button sometimes does not change back from the pressed state.

I don't change any colors, I just listen to native touch events and convert them to mine. So there is nothing I can do about it. I guess this behavior comes from iOS or Xamarin that the color does not reset while the page transition animation to open the page is still running - but that's just a guess.

As there is also a different bug with iOS Buttons handling Up/Down (see http://www.mrgestures.com/#Compatibility) you should not do this anyway. Use a Label or a Frame (if you need the rounded corners) or something else.
