### ISSUE TITLE
SwipeView + CollectionView + Mr Guestures on Android

### ISSUE THREAD

**Issue by ianvink** [MichaelRumpler/GestureSample#30]
I have a CollectionView and the cell is a Mr Guestures Grid with a TapCommand attached.

The Cell is wrapped in a SwipeView

On iOS you can tap the cell and swipe. On Android when you try to swipe, nothing happens. If I use a simple grid instead, the swipe works.

     <CollectionView>
         with cells of SwipeView around a Grid:
             <SwipeView>
               <Mr Guestures Grid with TappedCommand>

**Comment by ianvink** [comment]
It's a Xamarin Forms bug:

https://github.com/xamarin/Xamarin.Forms/issues/11333

**Comment by MichaelRumpler** [comment]
Those are the best ;-)

The CollectionView needs to handle touch gestures, the SwipeView and the TapGestureRecognizer too. Those interactions are always difficult to debug, But if it's contained within XF, then they have a better chance of finding it than when it spans two libraries.
