### ISSUE TITLE
iOS Pan Gesture Recognizer Crashing

### ISSUE THREAD

**Issue by AnthonyIacono** [MichaelRumpler/GestureSample#31]
Using MR.Gestures version 2.1.3 with a license

Getting a crash when scrolling aggressively through a ScrollView on iOS in iOSEventArgsHelper.GetViewPosition (null reference exception)

I don't use any pan gesture recognizers on the screen, so I'm not sure why it happens.

Thanks for your help!

**Comment by MichaelRumpler** [comment]
Sorry, but this is not enough information.

Please send me a repro project and the complete exception.

**Comment by AnthonyIacono** [comment]
@MichaelRumpler I'll get one together soon. If it helps, this is with a special scroll view that basically gets rid of elements as they go out of view. So I think basically it happens when one of those elements goes out of view and gets removed right as the pan event is being handled on the element.

I think a general improvement that could help in situations like this is to add some null checks around that element just to prevent accidentally crashing if something mid-pan is removed (similarly, other events probably apply here).
