### ISSUE TITLE
Panning/Panned and all other events stops working after first use

### ISSUE THREAD

**Issue by isoindisystems** [MichaelRumpler/GestureSample#32]
Hello!
I have a strange bug on iOS, after the onpanned event got fired for the first time, all events stop working on the stacklayout.
I´m using the latest version of mrgestures and on android all is working fine.
The issue came with the upgrade to xamarin forms 5 and from mr gestures 1.5.2 to 2.3.1.
We have absolutely no plan how to solve this, I hope you can give us an advice.

best regards!

**Comment by MichaelRumpler** [comment]
Those are very big version steps you made there. Can you send me a repro project? From your description I cannot know what causes this.

**Comment by isoindisystems** [comment]
I can´t share you the full project due to an NDA, but I can share you a snipped how the events got registered.

**Comment by MichaelRumpler** [comment]
I don't want your full project. I want a repro project. That is a minimal project which only shows the problem you get and nothing else.

Create a new project or check out the GestureSample and add a test page there. Copy only the code related to MR.Gestures to that page and see if you can reproduce it.

**Comment by isoindisystems** [comment]
Ok, I will do that.
What is also interesting is that the app crashes when I try to put a breakpoint into mr geastures events.

**Comment by isoindisystems** [comment]
With a fresh project I cant reproduce it.
Can we do a quick teamviewer session?

**Comment by MichaelRumpler** [comment]
From the problem description you may have removed the line which sets the `LicenseKey`. Could you check if you still set it in the `AppDelegate`?

**Comment by isoindisystems** [comment]
Yes, I checked the license key, all is set properly.

**Comment by isoindisystems** [comment]
Hello, we really need your support here, the component that is not working anymore is a critical function.
We have no I idea why all touch events are completely dead.

**Comment by isoindisystems** [comment]
I found the issue:
The problem were two interfering events: One of MRGestures and one of iOS (InteractivePopGestureRecognizer).
There is a simple solution using a custom page renderer:

```
[assembly: ExportRenderer(typeof(ContentPage), typeof(NoInteractivePopGestureRecognizer))]
namespace Mobile.iOS.Renderers
{
    public class NoInteractivePopGestureRecognizer: PageRenderer
    {
        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            if (ViewController != null && ViewController.NavigationController != null)
                ViewController.NavigationController.InteractivePopGestureRecognizer.Enabled = false;
        }
    }
}
```

**Comment by MichaelRumpler** [comment]
Thanks for letting us know!

The `InteractivePopGestureRecognizer` is used on a `NavigationPage` and controls the gesture, which allows you to pop the top page when swiping from the left edge inside.
