### ISSUE TITLE
Xamarin Forms (IOS) license key invalid.

### ISSUE THREAD

**Issue by E75** [MichaelRumpler/GestureSample#33]
Hello!
I have a strange thing on iOS. 

After updating Visual studio to version 16.10.0, I get a license key error for IOS App version.
He says that the license is no longer valid, while it worked well in the past. Do you know how I can solve this, because it works fine for Android, but for IOS I can't get it to work anymore? 

FYI: the license key is in AppDelegate.cs, in the FinishedLaunching method. (as indicated in the documentation).

**Comment by MichaelRumpler** [comment]
What EXACTLY is the exception? Overwrite the license key and copy the rest here.

**Comment by E75** [comment]
@MichaelRumpler This is the exception.
![afbeelding](https://user-images.githubusercontent.com/9724772/123051883-81584180-d402-11eb-849e-969bb74dca73.png)

and these are the settings set on the IOS App. 
![afbeelding](https://user-images.githubusercontent.com/9724772/123052109-be243880-d402-11eb-89e7-5c1b18db6cf3.png)

**Comment by MichaelRumpler** [comment]
You did not buy a license for ![appname](https://user-images.githubusercontent.com/8309363/123612848-358f0900-d803-11eb-8d49-68e2edc66326.png)
So apparently you did not configure your app name right. See https://www.mrgestures.com/#HowToConfigureAppName

I check the CFBundleName first and only if that does not exist, then I take CFBundleDisplayName. Please check that you have the same values in your info.plist file.

**Comment by E75** [comment]
@MichaelRumpler That's a placeholder name for the screenshot, because I can't show the Appname for public.

What I said before. The key works for the "**android version**", but IOS version gives this error after updating to VS 2019 16.10.2

**Comment by MichaelRumpler** [comment]
Please write the correct app name to `CFBundleName` AND `CFBundleDisplayName` in the info.plist.

**Comment by E75** [comment]
@MichaelRumpler 

Thx for your help. I was missing the "CFBundleName" in the info.plist. So Apple has changed something internally
