### ISSUE TITLE
Pinch gesture inside a scroll

### ISSUE THREAD

**Issue by marcdieters** [MichaelRumpler/GestureSample#34]
Hello,

Is there any way to implement the pinch gesture for an image inside a scrollview ?
Whenever the XF detects a scroll, the pinch is stopped.

Pinching works perfect for the image when it's not inside the scroll view.

Thanks !

**Comment by MichaelRumpler** [comment]
As the `ScrollView` scrolls its contents, the finger on the `Image` actually doesn't move at all.

Such nested controls which use (and consume) the touch gestures on their own are always a problem and also not consistent on all platforms. You can try the `Pinching` gesture on the `ScrollView` and additional `Down`/`Up` on the `Image` to see if it was touched.
