### ISSUE TITLE
UWP Crashing unsure why

### ISSUE THREAD

**Issue by ssombat** [MichaelRumpler/GestureSample#35]
Getting the following:

Object reference not set to an instance of an object.   at MR.Gestures.UWP.EventArgs.UWPSwipeEventArgs..ctor(Point velocity, List`1 currentPointers, FrameworkElement view, Direction direction, PanEventArgs previous)   at MR.Gestures.UWP.UWPGestureHandler.OnManipulationCompleted(Point totalDistance, Point velocity)   at MR.Gestures.UWP.UWPGestureHandler.OnManipulationCompleted(GestureRecognizer sender, ManipulationCompletedEventArgs args)

I have seen this a few times will running my app. Unable to produce consistently. Any ideas what this could be?

**Comment by MichaelRumpler** [comment]
Not really. The only thing which could cause a NRE in that constructor is if PanEventArgs previous is null. But there should never be a swipe event without a previous pan.

Do you handle other gesture events on that element? Do you manipulate the view tree in some gesture event handlers?
