### ISSUE TITLE
Question: Is there a MouseMove event?

### ISSUE THREAD

**Issue by TomQv** [MichaelRumpler/GestureSample#37]
Would be needed in Windows and Mac-projects, just to track the location of the mouse pointer in a view.

**Comment by MichaelRumpler** [comment]
Not yet. Currently `Panning` is only raised when a mouse button is pressed.
But you're right, desktop apps definitely need this. I'll look at this.

**Comment by TomQv** [comment]
And MouseWheel? Didn't find it so far, but is also useful for desktop-apps.

**Comment by MichaelRumpler** [comment]
Yes, I'm working on both. I hope to release it next week.

**Comment by MichaelRumpler** [comment]
Now there is. In version 2.2.0 I added `MoveEntered`, `MouseMoved`, `MouseExited` and `ScrollWheelChanged`.
