### ISSUE TITLE
Crash in iOS 12

### ISSUE THREAD

**Issue by fusionconsulting** [MichaelRumpler/GestureSample#39]
I'm using MR Gestures in a project that needs to run on an iOS 12 device. I'm getting this error on tap:

-[MR_Gestures_iOS_DownUpGestureRecognizer buttonMask]: unrecognized selector sent to instance

Works fine on newer devices so I'm just hoping there is a workaround for the older OS version.

**Comment by MichaelRumpler** [comment]
The `buttonMask` is only available from iOS 13.4. I forgot to check for that.

I released version 2.2.1 which includes this check. Please test with that version and close this issue if it fixes it.

**Comment by fusionconsulting** [comment]
Thanks, working as expected on iOS12 with version 2.2.1
