### ISSUE TITLE
UWP: DisplayActionSheet is not blocking events

### ISSUE THREAD

**Issue by TomQv** [MichaelRumpler/GestureSample#41]
I have a MR.Gestures.ContentView containing an Image and some events.
In the Tapped-Event I open a  Xamarin.Forms.DisplayActionSheet() to let the user select some options.
The funny thing is, while the DisplayActionSheet() is open, the under laying ContentView is still receiving events. For example if the user selects one of the options in the DisplayActionSheet, the ContentView also receives a tapped-event.
On Android or iOS the DisplayActionSheet is blocking all other events, which is the correct behavior.
How can I block all events on ContentView  while DisplayActionSheet  is open on UWP?

**Comment by MichaelRumpler** [comment]
Yeah, UWP is a bit stupid in this regard. They even raise events for elements on pages lower on the navigation stack. I have to disable them when the Page where the MR.Gestures.Element is on disappears. But there's no event when an ActionSheet is displayed. The underlying Page and your ContentView are still visible. so I don't know how I could disable that.

I think it's easier for you to set a flag when you display the ActionSheet and check for that flag in your gesture event handlers. Is that an option?

**Comment by TomQv** [comment]
Yes, I'm using a flag currently.
Just thought, there was a more elegant solution.
Thanks.

**Comment by MichaelRumpler** [comment]
I just checked what XF does. They send a message to the platform code which shows a `Windows.UI.Xaml.Controls.Flyout`. I could listen to that message to get notified when the ActionSheet is displayed, but there is nothing when it is dismissed.
So I'd have to check on every event if such a `Flyout` is in front. But that would be a lot of work and probably also a performance degradation which I'm not willing to risk.
