### ISSUE TITLE
Andriod: Swipe gesture NullReference exception

### ISSUE THREAD

**Issue by shnaz** [MichaelRumpler/GestureSample#5]
Hey @MichaelRumpler, I experience nullreference exception when using Swipe gesture on MR.Gestures.AbsolutLayout, but only in Android, works fine in iOS.

Do you have any idea what the error is caused by?

Best regards

**Comment by MichaelRumpler** [comment]
This is fixed in version 1.4.1.

**Comment by japero** [comment]
Hi,
I am using 2.1.0 version and get this error. When I reverted to 2.0.0 error disappear. I am using MR.Gestures.ScrollView control.
