### ISSUE TITLE
Crash in MR.Gestures Android (1.4.1)

### ISSUE THREAD

**Issue by patook** [MichaelRumpler/GestureSample#6]
Hi - stack trace below. Frequency is rare (8 in 100,000)

System.InvalidOperationExceptionCollection was modified; enumeration operation may not execute.
System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)<aae96e2300b84d7080b3a6a2060eb1e8>:0
System.Collections.Generic.Dictionary<TKey, TValue>.ValueCollection.Enumerator.MoveNext()<aae96e2300b84d7080b3a6a2060eb1e8>:0
System.Linq.Enumerable.WhereSelectEnumerableIterator<TSource, TResult>.MoveNext()<f816f4ed7f534a6eb5698c6210a9ae03>:0
System.Linq.Buffer<TElement>.Buffer(IEnumerable<T> source)<f816f4ed7f534a6eb5698c6210a9ae03>:0
System.Linq.Enumerable.ToArray<TSource>(IEnumerable<T> source)<f816f4ed7f534a6eb5698c6210a9ae03>:0
MR.Gestures.Android.EventArgs.AndroidEventArgsHelper.GetTouches(IEnumerable<T> touches)<d293e6e9d0b642c9bef268c0be1c388a>:0
MR.Gestures.Android.EventArgs.AndroidLongPressEventArgs.AndroidLongPressEventArgs(IEnumerable<T> touches, long duration, View view)<d293e6e9d0b642c9bef268c0be1c388a>:0
MR.Gestures.Android.TapGestureListener.onLongPressing(IEnumerable<T> touches, long duration)<d293e6e9d0b642c9bef268c0be1c388a>:0
at MR.Gestures.Android.TapGestureDetector+<<OnTouchEvent>b__9_0>d.MoveNext () [0x000d6] in <d293e6e9d0b642c9bef268c0be1c388a>:0

**Comment by MichaelRumpler** [comment]
Fixed in 1.4.2.2.
