### ISSUE TITLE
SwipedCommand of ScrollView not working at Xamarin.iOS

### ISSUE THREAD

**Issue by YongqingKyleHuang** [MichaelRumpler/GestureSample#8]
Hi Michael,

I have tested Mr.Gestures for SwipedCommand of ScrollView :
1. By Android, it works
2. By iOS, it doesn't

How can I resolve this problem?
Is this normal for the test version of Mr.Gestures?

Thanks in advance,
Yongqing Huang

**Comment by MichaelRumpler** [comment]
It works in the GestureSample.
Did you try that app on your device too? Does it work for you?
If you don't have a license key, then you can change the name of your app to GestureSample and try with the key of that app.

**Comment by MichaelRumpler** [comment]
Not reproducible and no answer.
